name: Auto Sync Branch

on:
  push:
    branches:
      - source1  # Trigger on pushes to source1
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop  # Checkout the develop branch where the workflow file resides

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch source1 branch
        run: |
          git fetch origin source1
          git checkout -b temp1 origin/source1

      - name: Create temporary branch
        run: |
          git checkout -b temp1
          git merge origin/source1 --no-commit --no-ff || echo "Merge failed"

      - name: Check for merge conflicts
        id: check_conflicts
        run: |
          if git ls-files -u | grep -q .; then
            echo "Merge conflicts detected."
            echo "conflicts=true" >> $GITHUB_ENV
            git merge --abort  # Abort the merge
          else
            echo "No conflicts detected."
            echo "conflicts=false" >> $GITHUB_ENV
            git commit -m "Merged source1 into temp1"
          fi

      - name: Sync to target1 (if no conflicts)
        if: env.conflicts == 'false'
        run: |
          git checkout target1
          git merge temp1
          git push origin target1

      - name: Clean up temporary branch
        if: env.conflicts == 'false'
        run: |
          git branch -D temp1
